import {useEffect,useState} from 'react';
import {Check,ChevronLeft,History,Minus,Plus,X} from 'lucide-react';
import {useLiveQuery} from 'dexie-react-hooks';
import type {CountSession,CountSessionItem,CountTransaction} from '../types';
import {formatThaiDateTime} from '../utils/stock';
import {db} from '../db/database';
import {filterSessionsByUser, getCurrentUser} from '../services/authService';

export function StockCountHeader({session,total,counted}:{session:CountSession;total:number;counted:number}){
  const pct = total ? Math.round(counted / total * 100) : 0;
  const currentUser = getCurrentUser();
  const allSessions = (useLiveQuery(() => db.countSessions.where('status').equals('ACTIVE').toArray(), []) || []) as CountSession[];
  const sessions = filterSessionsByUser(allSessions, currentUser);
  const choose = (id:number) => {localStorage.setItem('audit-selected-session', String(id)); location.reload()};
  return <>
    <section className="panel mb-5">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">BRANCH COUNT</p><h2 className="section-title">เลือกสาขาที่ต้องการนับ</h2></div><button className="btn-secondary" onClick={() => location.assign('/movement')}>+ เพิ่มสาขา</button></div>
      <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{sessions.map(branch => <button key={branch.id} className={branch.id === session.id ? 'rounded-2xl border-2 border-rose-600 bg-rose-50 p-4 text-left' : 'rounded-2xl border border-slate-200 bg-white p-4 text-left hover:border-rose-300'} onClick={() => choose(branch.id!)}><b className="block text-base">{branch.branchName}</b><span className="mt-1 block font-mono text-xs text-slate-500">{branch.sessionNumber}</span><span className="mt-2 block text-xs font-bold text-rose-700">{branch.id === session.id ? 'กำลังนับสาขานี้' : 'คลิกเพื่อเข้าสาขานี้'}</span></button>)}</div>
    </section>
    <section className="overflow-hidden rounded-3xl bg-slate-950 p-5 text-white shadow-xl sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-white/10 px-3 py-1 text-xs">รอบกำลังใช้งาน</span><h2 className="mt-3 text-2xl font-black">{session.branchName}</h2><p className="mt-1 font-mono text-sm text-slate-300">{session.sessionNumber}</p></div><div className="text-right"><span className="text-xs text-slate-400">วันที่ตรวจ</span><b className="block">{new Date(session.countDate).toLocaleDateString('th-TH')}</b></div></div><div className="mt-6 grid grid-cols-3 gap-3"><Metric label="ทั้งหมด" value={total}/><Metric label="นับแล้ว" value={counted}/><Metric label="ยังไม่นับ" value={total-counted}/></div><div className="mt-5 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-rose-400 transition-all" style={{width:`${pct}%`}}/></div><b>{pct}%</b></div></section>
  </>;
}
function Metric({label,value}:{label:string;value:number}){return <div><b className="text-xl">{value}</b><span className="block text-xs text-slate-400">{label}</span></div>}

export function ProductCountCard({item,categoryName,transactions,onClick}:{item:CountSessionItem;categoryName?:string;transactions:CountTransaction[];onClick:()=>void}){
  const latest = [...transactions].sort((a,b) => +new Date(b.countedAt) - +new Date(a.countedAt))[0];
  const total = transactions.reduce((s,t) => s + t.signedQuantity, 0);
  return <button onClick={onClick} className="product-row text-left"><div className="min-w-0"><h3>{item.productNameSnapshot}</h3><p>{categoryName || 'ไม่ระบุหมวด'} · รหัส {item.productCode} · หน่วย {item.unitSnapshot}</p>{latest ? <p>ล่าสุด {new Date(latest.countedAt).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})} น.</p> : <p>แตะเพื่อเริ่มนับ</p>}</div><div className="product-row-status"><span className={latest ? 'status-counted' : 'status-new'}>{latest ? 'นับแล้ว' : 'ยังไม่นับ'}</span>{latest && <b className={total < 0 ? 'text-red-600' : 'text-slate-900'}>{total.toLocaleString('th-TH',{maximumFractionDigits:3})}</b>}</div></button>;
}

export function RecentCountHistory({transactions}:{transactions:CountTransaction[]}){return <section className="panel"><h2 className="section-title"><History/>ประวัติการนับล่าสุด</h2>{[...transactions].sort((a,b)=>+new Date(b.countedAt)-+new Date(a.countedAt)).slice(0,8).map(t=><div key={t.id} className="flex items-center justify-between border-b border-slate-100 py-4 last:border-0"><div><b>{t.productNameSnapshot}</b><p className="mt-1 text-xs text-slate-500">{t.countedBy} · {new Date(t.countedAt).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})} น.</p></div><b className={t.action==='ADD'?'text-emerald-600':'text-red-600'}>{t.action==='ADD'?'+':'−'}{t.quantity.toLocaleString('th-TH',{maximumFractionDigits:3})}</b></div>)}</section>}

export function CountStepModal({item,transactions,auditor,onClose,onSave}:{item:CountSessionItem;transactions:CountTransaction[];auditor:string;onClose:()=>void;onSave:(v:{action:'ADD'|'SUBTRACT';quantity:number;note:string})=>void}){
  const [step,setStep]=useState(1),[action,setAction]=useState<'ADD'|'SUBTRACT'|null>(null),[value,setValue]=useState(''),[note,setNote]=useState('');
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(step===2&&/^[0-9.]$/.test(e.key))press(e.key);if(e.key==='Escape')onClose()};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)});
  const press=(x:string)=>{if(x==='back')return setValue(v=>v.slice(0,-1));if(x==='clear')return setValue('');setValue(v=>{if(x==='.'&&v.includes('.'))return v;if(x==='.'&&!v)return'0.';if(v.includes('.')&&v.split('.')[1].length>=3)return v;if(v==='0'&&x!=='.')return x;return v+x})};
  const qty=Number(value);
  const chooseAction=(nextAction:'ADD'|'SUBTRACT')=>{setAction(nextAction);setStep(2)};
  return <div className="modal-backdrop"><div className="modal-card count-modal-card max-w-xl"><div className="flex items-center justify-between gap-3"><span className="eyebrow">ขั้นตอนที่ {step}/2</span><button aria-label="ปิด" className="icon-btn" onClick={onClose}><X/></button></div><h2 className="mt-3 text-xl font-black">{item.productNameSnapshot}</h2>{step===1&&<><CountAttemptList transactions={transactions} compact/><CountActionStep value={action} onChange={chooseAction}/></>} {step===2&&<><CountKeypadStep value={value} action={action!} onPress={press}/><CountAttemptList transactions={transactions}/><label className="mt-4 block text-sm font-bold">หมายเหตุ (ไม่บังคับ)<textarea className="input mt-2 min-h-20" value={note} onChange={e=>setNote(e.target.value)}/></label></>}<div className={`modal-actions mt-5 grid gap-3 ${step===1?'grid-cols-1':'grid-cols-2'}`}>{step===1?<button className="btn-secondary" onClick={onClose}>ยกเลิก</button>:<><button className="btn-secondary" onClick={()=>setStep(1)}><ChevronLeft/>ย้อนกลับ</button><button className="btn-primary" disabled={!value||!Number.isFinite(qty)||qty<=0} onClick={()=>onSave({action:action!,quantity:qty,note})}><Check/>บันทึกข้อมูล</button></>}</div></div></div>;
}

export function CountActionStep({value,onChange}:{value:'ADD'|'SUBTRACT'|null;onChange:(v:'ADD'|'SUBTRACT')=>void}){return <div className="mt-6 grid gap-3 sm:grid-cols-2"><button className={`choice-card ${value==='ADD'?'choice-active-add':''}`} onClick={()=>onChange('ADD')}><Plus/><b>เพิ่มจำนวน</b><span>เมื่อพบสินค้าและต้องการเพิ่มยอดนับ</span></button><button className={`choice-card ${value==='SUBTRACT'?'choice-active-sub':''}`} onClick={()=>onChange('SUBTRACT')}><Minus/><b>ลบจำนวน</b><span>เมื่อนับเกินหรือต้องการหักยอด</span></button></div>}
export function CountAttemptList({transactions,compact=false}:{transactions:CountTransaction[];compact?:boolean}){const rows=[...transactions].sort((a,b)=>+new Date(a.countedAt)-+new Date(b.countedAt));return <section className={`count-attempt-list ${compact?'count-attempt-compact':''} mt-4 rounded-2xl bg-slate-50 p-4`}><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-black text-slate-800">ประวัติการนับรายการนี้</h3>{rows.length>0&&<span className="badge">{rows.length} ครั้ง</span>}</div>{rows.length?rows.map((t,i)=><div key={t.id} className="count-attempt-row mt-3 flex items-center justify-between gap-3 border-t border-slate-200 pt-3"><div><b className="text-sm">ครั้งที่ {i+1}</b><p className="mt-1 text-xs text-slate-500">เวลา {formatThaiDateTime(t.countedAt)}</p></div><div className="text-right"><b className={t.action==='ADD'?'text-emerald-600':'text-red-600'}>{t.action==='ADD'?'+':'-'}{t.quantity.toLocaleString('th-TH',{maximumFractionDigits:3})}</b><p className="mt-1 text-xs text-slate-500">ยอดหลัง {t.newTotal.toLocaleString('th-TH',{maximumFractionDigits:3})}</p></div></div>):<p className="mt-2 text-xs text-slate-500">ยังไม่มีประวัติการนับสินค้านี้</p>}</section>}
export function CountKeypadStep({value,action,onPress}:{value:string;action:'ADD'|'SUBTRACT';onPress:(x:string)=>void}){return <div className="mt-5"><div className="rounded-2xl bg-slate-950 p-4 text-center text-white"><span className="text-xs text-slate-400">{action==='ADD'?'เพิ่มจำนวน':'ลบจำนวน'}</span><b className="mt-1 block text-4xl">{value||'0'}</b></div><div className="mt-3 grid grid-cols-3 gap-2">{['1','2','3','4','5','6','7','8','9','.','0','back'].map(x=><button key={x} className="key-btn" onClick={()=>onPress(x)}>{x==='back'?'⌫':x}</button>)}</div><button className="btn-quiet mt-2 w-full" onClick={()=>onPress('clear')}>C ล้างทั้งหมด</button></div>}
export function CountConfirmStep(){return null}
export function CountHistoryDrawer({item,transactions,onClose}:{item:CountSessionItem;transactions:CountTransaction[];onClose:()=>void}){return <div className="modal-backdrop"><div className="modal-card max-w-2xl"><div className="flex justify-between"><div><p className="eyebrow">AUDIT TRAIL</p><h2 className="text-xl font-black">{item.productNameSnapshot}</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="table-wrap mt-5"><table><thead><tr><th>ครั้งที่</th><th>รายการ</th><th>จำนวน</th><th>ก่อน</th><th>หลัง</th><th>วันเวลา</th><th>ผู้บันทึก</th><th>หมายเหตุ</th></tr></thead><tbody>{[...transactions].sort((a,b)=>+new Date(a.countedAt)-+new Date(b.countedAt)).map((t,i)=><tr key={t.id}><td>{i+1}</td><td>{t.action==='ADD'?'เพิ่ม':'ลบ'}</td><td>{t.quantity}</td><td>{t.previousTotal}</td><td>{t.newTotal}</td><td>{formatThaiDateTime(t.countedAt)}</td><td>{t.countedBy}</td><td>{t.note||'-'}</td></tr>)}</tbody></table></div></div></div>}
