import Dexie,{type EntityTable} from 'dexie';
import type {AllowanceImport,AuditUser,CountSession,CountSessionItem,CountTransaction,ExportRecord,MovementImport,MovementItem,ParsedMovement,Product} from '../types';
type MovementDraft={id:'movement';fileName:string;rows:ParsedMovement[];updatedAt:Date};
const baseSchema={products:'&productCode,productName,categoryName,isActive,updatedAt',allowanceImports:'++id,importedAt',movementImports:'++id,importedAt',movementItems:'++id,movementImportId,productCode,matched,[movementImportId+productCode]',countSessions:'++id,&sessionNumber,status,createdAt',countSessionItems:'++id,sessionId,productCode,&[sessionId+productCode]',countTransactions:'++id,sessionId,productCode,countedAt,[sessionId+productCode]'};
export class AuditDatabase extends Dexie {
  products!:EntityTable<Product,'productCode'>;allowanceImports!:EntityTable<AllowanceImport,'id'>;movementImports!:EntityTable<MovementImport,'id'>;movementItems!:EntityTable<MovementItem,'id'>;countSessions!:EntityTable<CountSession,'id'>;countSessionItems!:EntityTable<CountSessionItem,'id'>;countTransactions!:EntityTable<CountTransaction,'id'>;movementDrafts!:EntityTable<MovementDraft,'id'>;exportRecords!:EntityTable<ExportRecord,'id'>;auditUsers!:EntityTable<AuditUser,'id'>;
  constructor(){super('AuditStockCountDB');this.version(1).stores(baseSchema);this.version(2).stores({...baseSchema,movementDrafts:'&id,updatedAt'});this.version(3).stores({...baseSchema,movementDrafts:'&id,updatedAt',exportRecords:'++id,exportType,sessionId,branchName,createdAt'});this.version(4).stores({...baseSchema,movementDrafts:'&id,updatedAt',exportRecords:'++id,exportType,sessionId,branchName,createdAt',auditUsers:'++id,&username,role,isActive'});this.version(5).stores({...baseSchema,movementDrafts:'&id,updatedAt',exportRecords:'++id,exportType,sessionId,branchName,createdAt',auditUsers:'++id,&username,role,isActive',sharePointBackupJobs:'&id,status,nextAttemptAt,createdAt',appSettings:'&key,updatedAt'});this.version(6).stores({...baseSchema,movementDrafts:'&id,updatedAt',exportRecords:'++id,exportType,sessionId,branchName,createdAt',auditUsers:'++id,&username,role,isActive',sharePointBackupJobs:null,appSettings:null});}
}
export const db=new AuditDatabase();
