import {useEffect,useMemo,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {useNavigate} from 'react-router-dom';
import * as XLSX from 'xlsx';
import {db} from '../db/database';
import type {CountSession,ParsedMovement} from '../types';
import {matchMovementWithProducts,parseMovementWorkbook} from '../utils/stock';
import {auditRepository} from '../services/auditRepository';
import {saveWorkbookExport} from '../services/exportService';
import {FileDrop,MatchSummaryCards,MovementImportPreview} from '../components/ImportUI';
import {Page} from './AllowanceImportPage';
export default function MovementImportPage(){
  const products=useLiveQuery(()=>db.products.toArray(),[])||[];
  const active=useLiveQuery(()=>db.countSessions.where('status').equals('ACTIVE').last(),[]) as CountSession|undefined;
  const draft=useLiveQuery(()=>db.movementDrafts.get('movement'),[]);
  const [rows,setRows]=useState<ParsedMovement[]>([]),[file,setFile]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
  const [form,setForm]=useState({branchName:'',countDate:new Date().toISOString().slice(0,10),auditorName:'',note:''});
  const nav=useNavigate();const matchedCount=useMemo(()=>rows.filter(r=>r.matched).length,[rows]),selectedCount=useMemo(()=>rows.filter(r=>r.selected&&r.matched).length,[rows]),missing=useMemo(()=>rows.filter(r=>!r.matched&&r.status==='valid'),[rows]);
  useEffect(()=>{if(draft&&!rows.length){setFile(draft.fileName);setRows(draft.rows);setMessage('กู้คืนไฟล์รายการเคลื่อนไหวที่ยังไม่ได้ยืนยันแล้ว');}},[draft,rows.length]);
  const persistDraft=(draftFile:string,nextRows:ParsedMovement[])=>db.movementDrafts.put({id:'movement',fileName:draftFile,rows:nextRows,updatedAt:new Date()});
  const updateRows=(updater:(current:ParsedMovement[])=>ParsedMovement[])=>setRows(current=>{const next=updater(current);void persistDraft(file,next);return next;});
  const createBranch=async()=>{if(!form.branchName||!form.auditorName)return;try{setSaving(true);await auditRepository.createSession({...form,countDate:new Date(form.countDate)});setMessage(`สร้างสาขา ${form.branchName} แล้ว สามารถอัปโหลดไฟล์เคลื่อนไหวได้`);}catch(e){setMessage(e instanceof Error?e.message:'สร้างสาขาไม่สำเร็จ')}finally{setSaving(false)}};
  const handle=async(f:File)=>{try{const parsed=matchMovementWithProducts(parseMovementWorkbook(await f.arrayBuffer()),products);setFile(f.name);setRows(parsed);await persistDraft(f.name,parsed);setMessage(parsed.some(r=>r.matched)?`จับคู่สำเร็จ พบใน Allowance ${parsed.filter(r=>r.matched).length} รายการ`:'ไม่พบรหัสที่ตรงกับ Allowance กรุณานำเข้า Allowance ก่อน');}catch(e){setRows([]);setMessage(e instanceof Error?e.message:'อ่านไฟล์ไม่สำเร็จ')}};
  const selectAll=()=>{if(!matchedCount)return;updateRows(current=>current.map(row=>({...row,selected:!!row.matched})));setMessage(`เลือกทั้งหมด ${matchedCount} รายการแล้ว`)};const clearAll=()=>{updateRows(current=>current.map(row=>({...row,selected:false})));setMessage('ยกเลิกการเลือกทั้งหมดแล้ว')};
  const useRows=async()=>{if(!active){setMessage('กรุณาสร้างชื่อสาขาก่อน');return;}if(!selectedCount){setMessage('กรุณาเลือกรายการอย่างน้อย 1 รายการ');return;}try{setSaving(true);await auditRepository.addMovement(file,rows,active,active.auditorName);await db.movementDrafts.delete('movement');nav('/count');}catch(e){setMessage(e instanceof Error?`นำรายการไปนับไม่สำเร็จ: ${e.message}`:'นำรายการไปนับไม่สำเร็จ')}finally{setSaving(false)}};
  const exportMissing=async()=>{const ws=XLSX.utils.json_to_sheet(missing.map(x=>({'รหัสสินค้า':x.productCode,'ชื่อสินค้า':x.sourceProductName,'หน่วยนับ':x.sourceUnit,'เหตุผล':x.matchReason})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'ไม่พบใน Allowance');const stamp=new Date().toISOString().slice(0,16).replace('T','_').replace(':','');await saveWorkbookExport(wb,`Unmatched_Allowance_${stamp}.xlsx`,'UNMATCHED',active?.id,active?.branchName);setMessage('บันทึกไฟล์ลงประวัติและดาวน์โหลดแล้ว')};
  if(!active)return <Page title="สร้างสาขาก่อนนำเข้า" subtitle="ต้องระบุสาขาและผู้ตรวจนับก่อนอัปโหลดไฟล์รายการเคลื่อนไหว"><section className="panel mx-auto max-w-xl"><form onSubmit={e=>{e.preventDefault();createBranch()}}><div className="grid gap-4"><label>ชื่อสาขา<input className="input mt-1" value={form.branchName} onChange={e=>setForm({...form,branchName:e.target.value})} required/></label><label>วันที่ตรวจนับ<input className="input mt-1" type="date" value={form.countDate} onChange={e=>setForm({...form,countDate:e.target.value})} required/></label><label>ชื่อผู้ตรวจนับ<input className="input mt-1" value={form.auditorName} onChange={e=>setForm({...form,auditorName:e.target.value})} required/></label><label>หมายเหตุ<textarea className="input mt-1 min-h-20" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="btn-primary" disabled={saving}>{saving?'กำลังสร้าง...':'สร้างสาขาและรอบนับ'}</button></div></form></section>{message&&<div className="notice">{message}</div>}</Page>;
  return <Page title="ไฟล์รายการเคลื่อนไหว" subtitle="อ่าน A = รหัสสินค้า, C = ชื่อสินค้า, D = หน่วยนับ"><section className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-950 p-4 text-white"><div><span className="text-xs text-slate-400">สาขาปัจจุบัน</span><b className="block text-lg">{active.branchName}</b><span className="text-xs text-slate-300">{active.sessionNumber} · {active.auditorName}</span></div><button className="btn-secondary" onClick={async()=>{await db.countSessions.update(active.id!,{status:'CLOSED',updatedAt:new Date()});setRows([])}}>สร้างสาขา/รอบใหม่</button></section><section className="panel"><FileDrop label="เลือกไฟล์รายการเคลื่อนไหว" onFile={handle}/>{rows.length>0&&<><div className="mt-5"><MatchSummaryCards items={[{label:'ทั้งหมด',value:rows.length},{label:'พบ Allowance',value:matchedCount},{label:'ไม่พบ',value:missing.length,tone:'text-amber-600'},{label:'ซ้ำ',value:rows.filter(r=>r.status==='duplicate').length},{label:'ไม่ครบ',value:rows.filter(r=>r.status==='invalid').length},{label:'เลือกไปนับ',value:selectedCount,tone:'text-rose-700'}]}/></div><div className="mt-5 flex flex-wrap gap-2"><button type="button" className="btn-quiet" disabled={!matchedCount} onClick={selectAll}>เลือกทั้งหมด ({matchedCount})</button><button type="button" className="btn-quiet" disabled={!selectedCount} onClick={clearAll}>ยกเลิกทั้งหมด</button><button type="button" className="btn-quiet" disabled={!missing.length} onClick={exportMissing}>Export รายการไม่พบ</button></div><div className="mt-4"><MovementImportPreview rows={rows} onToggle={i=>updateRows(current=>current.map((row,index)=>index===i&&row.matched?{...row,selected:!row.selected}:row))}/></div><button type="button" className="btn-primary mt-4 w-full" disabled={!selectedCount||saving} onClick={useRows}>{saving?'กำลังนำรายการเข้ารอบนับ...':`นำรายการที่เลือกไปนับสต็อก (${selectedCount})`}</button></>}</section>{message&&<div className="notice">{message}</div>}</Page>
}
