import {useMemo,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {Download,History,Plus,Search,Trash2} from 'lucide-react';
import {db} from '../db/database';
import type {CountSessionItem} from '../types';
import {auditRepository} from '../services/auditRepository';
import {exportCountSession} from '../services/exportService';
import {ConfirmDialog} from '../components/ConfirmDialog';
import {Toast} from '../components/Toast';
import {ExportHistory} from '../components/ExportHistory';
import {CountHistoryDrawer,CountStepModal,ProductCountCard,RecentCountHistory,StockCountHeader} from '../components/CountUI';
import {Empty,Page} from './AllowanceImportPage';
export default function StockCountPage(){
  const selectedSessionId=Number(localStorage.getItem('audit-selected-session'))||undefined;
  const session=useLiveQuery(()=>selectedSessionId?db.countSessions.get(selectedSessionId):db.countSessions.where('status').equals('ACTIVE').last(),[selectedSessionId]);
  const items=useLiveQuery(()=>session?.id?db.countSessionItems.where('sessionId').equals(session.id).toArray():[],[session?.id])||[];
  const transactions=useLiveQuery(()=>session?.id?db.countTransactions.where('sessionId').equals(session.id).toArray():[],[session?.id])||[];
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('uncounted'),[selected,setSelected]=useState<CountSessionItem>(),[history,setHistory]=useState<CountSessionItem>(),[clear,setClear]=useState(false),[toast,setToast]=useState('');
  const rows=useMemo(()=>items.map(item=>{const tx=transactions.filter(t=>t.productCode===item.productCode),total=tx.reduce((s,t)=>s+t.signedQuantity,0),latest=[...tx].sort((a,b)=>+new Date(b.countedAt)-+new Date(a.countedAt))[0];return{item,tx,total,latest}}).filter(x=>x.item.productNameSnapshot.toLowerCase().includes(query.toLowerCase())).filter(x=>filter==='all'||filter==='new'&&!x.latest||filter==='counted'&&x.latest||filter==='zero'&&x.latest&&x.total===0||filter==='negative'&&x.total<0).sort((a,b)=>sort==='uncounted'?Number(!!a.latest)-Number(!!b.latest):sort==='latest'?(+new Date(b.latest?.countedAt||0)-+new Date(a.latest?.countedAt||0)):sort==='za'?b.item.productNameSnapshot.localeCompare(a.item.productNameSnapshot,'th'):a.item.productNameSnapshot.localeCompare(b.item.productNameSnapshot,'th')),[items,transactions,query,filter,sort]);
  if(!session)return <Page title="นับสต็อก" subtitle="สร้างสาขาและรอบนับจากเมนูไฟล์รายการเคลื่อนไหว"><section className="panel"><Empty text="ยังไม่มีรอบนับที่กำลังใช้งาน กรุณาสร้างสาขาก่อนนำเข้าไฟล์รายการเคลื่อนไหว"/></section><div className="mt-5"><ExportHistory/></div></Page>;
  const save=async(v:{action:'ADD'|'SUBTRACT';quantity:number;note:string})=>{const tx=transactions.filter(t=>t.productCode===selected!.productCode),old=tx.reduce((s,t)=>s+t.signedQuantity,0),signed=v.action==='ADD'?v.quantity:-v.quantity;await auditRepository.addTransaction({sessionId:session.id!,productCode:selected!.productCode,productNameSnapshot:selected!.productNameSnapshot,action:v.action,quantity:v.quantity,signedQuantity:signed,previousTotal:old,newTotal:old+signed,note:v.note,countedAt:new Date(),countedBy:session.auditorName});setSelected(undefined);setToast('บันทึกรายการสำเร็จ');setTimeout(()=>setToast(''),2500)};
  const doExport=async()=>{await exportCountSession(session,items,transactions);setToast('บันทึกไฟล์ลงประวัติและดาวน์โหลดแล้ว');setTimeout(()=>setToast(''),2500)};
  return <Page title="นับสต็อก" subtitle="แตะชื่อสินค้าเพื่อบันทึกยอดแบบ 3 ขั้นตอน"><StockCountHeader session={session} total={items.length} counted={new Set(transactions.map(t=>t.productCode)).size}/><div className="mt-5 grid gap-5 xl:grid-cols-[1.6fr_1fr]"><section className="panel"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><label className="input-shell"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาชื่อสินค้า"/></label><select className="input" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทั้งหมด</option><option value="new">ยังไม่นับ</option><option value="counted">นับแล้ว</option><option value="zero">ยอดเป็นศูนย์</option><option value="negative">ยอดติดลบ</option></select><select className="input" value={sort} onChange={e=>setSort(e.target.value)}><option value="uncounted">ยังไม่นับก่อน</option><option value="latest">นับล่าสุด</option><option value="az">ชื่อสินค้า ก-ฮ</option><option value="za">ชื่อสินค้า ฮ-ก</option></select></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{rows.map(x=><div key={x.item.productCode} className="relative"><ProductCountCard item={x.item} transactions={x.tx} onClick={()=>setSelected(x.item)}/>{x.latest&&<button aria-label="ดูประวัติ" className="absolute bottom-3 left-3 rounded-lg p-2 text-slate-400 hover:bg-slate-100" onClick={()=>setHistory(x.item)}><History size={17}/></button>}</div>)}</div>{!rows.length&&<Empty text="ไม่พบสินค้าตามเงื่อนไข"/>}</section><aside className="space-y-5"><section className="panel"><h2 className="section-title">จัดการรอบนับ</h2><div className="grid gap-2"><button className="btn-primary" onClick={doExport}><Download/>Export Excel</button><button className="btn-secondary" onClick={()=>document.getElementById('recent')?.scrollIntoView({behavior:'smooth'})}><History/>ดูประวัติการนับ</button><button className="btn-secondary" onClick={()=>location.assign('/movement')}><Plus/>เริ่มรอบนับใหม่</button><button className="btn-danger-outline" onClick={()=>setClear(true)}><Trash2/>ล้างข้อมูลรอบปัจจุบัน</button></div></section><ExportHistory/><div id="recent"><RecentCountHistory transactions={transactions}/></div></aside></div>{selected&&<CountStepModal item={selected} transactions={transactions.filter(t=>t.productCode===selected.productCode)} auditor={session.auditorName} onClose={()=>setSelected(undefined)} onSave={save}/>} {history&&<CountHistoryDrawer item={history} transactions={transactions.filter(t=>t.productCode===history.productCode)} onClose={()=>setHistory(undefined)}/>}<ConfirmDialog open={clear} title="ล้างข้อมูลรอบปัจจุบัน?" detail="รายการสินค้าและประวัติการนับในรอบนี้จะถูกลบ การกระทำนี้ย้อนกลับไม่ได้" onCancel={()=>setClear(false)} onConfirm={async()=>{await auditRepository.clearSession(session.id!);setClear(false);setToast('ล้างข้อมูลรอบปัจจุบันแล้ว')}}/><Toast message={toast}/></Page>
}
export function ExportExcelButton(){return null}
