import {useEffect,useMemo,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {useNavigate} from 'react-router-dom';
import * as XLSX from 'xlsx';
import {db} from '../db/database';
import type {CountSession,ParsedMovement} from '../types';
import {matchMovementWithProducts,parseMovementWorkbook} from '../utils/stock';
import {auditRepository} from '../services/auditRepository';
import {FileDrop,MatchSummaryCards,MovementImportPreview} from '../components/ImportUI';
import {Page} from './AllowanceImportPage';

export default function MovementImportPage(){
  const products=useLiveQuery(()=>db.products.toArray(),[])||[];
  const active=useLiveQuery(()=>db.countSessions.where('status').equals('ACTIVE').last(),[]) as CountSession|undefined;
  const draft=useLiveQuery(()=>db.movementDrafts.get('movement'),[]);
  const [rows,setRows]=useState<ParsedMovement[]>([]),[file,setFile]=useState(''),[message,setMessage]=useState(''),[sessionOpen,setSessionOpen]=useState(false),[saving,setSaving]=useState(false);
  const [form,setForm]=useState({branchName:'',countDate:new Date().toISOString().slice(0,10),auditorName:'',note:''});
  const nav=useNavigate();
  const matchedCount=useMemo(()=>rows.filter(r=>r.matched).length,[rows]);
  const selectedCount=useMemo(()=>rows.filter(r=>r.selected&&r.matched).length,[rows]);
  const missing=useMemo(()=>rows.filter(r=>!r.matched&&r.status==='valid'),[rows]);
  useEffect(()=>{if(draft&&!rows.length){setFile(draft.fileName);setRows(draft.rows);setMessage('กู้คืนไฟล์รายการเคลื่อนไหวที่ยังไม่ได้ยืนยันแล้ว');}},[draft,rows.length]);
  const persistDraft=(draftFile:string,nextRows:ParsedMovement[])=>db.movementDrafts.put({id:'movement',fileName:draftFile,rows:nextRows,updatedAt:new Date()});
  const updateRows=(updater:(current:ParsedMovement[])=>ParsedMovement[])=>setRows(current=>{const next=updater(current);void persistDraft(file,next);return next;});
  const handle=async(f:File)=>{try{const parsed=matchMovementWithProducts(parseMovementWorkbook(await f.arrayBuffer()),products);setFile(f.name);setRows(parsed);await persistDraft(f.name,parsed);setMessage(parsed.some(r=>r.matched)?`จับคู่สำเร็จ พบใน Allowance ${parsed.filter(r=>r.matched).length} รายการ`:'ไม่พบรหัสที่ตรงกับ Allowance กรุณาตรวจสอบว่าได้นำเข้าไฟล์ Allowance แล้ว');}catch(e){setRows([]);setMessage(e instanceof Error?e.message:'อ่านไฟล์ไม่สำเร็จ')}};
  const selectAll=()=>{if(!matchedCount){setMessage('ไม่มีรายการที่พบใน Allowance ให้เลือก');return;}updateRows(current=>current.map(row=>({...row,selected:!!row.matched})));setMessage(`เลือกทั้งหมด ${matchedCount} รายการแล้ว`)};
  const clearAll=()=>{updateRows(current=>current.map(row=>({...row,selected:false})));setMessage('ยกเลิกการเลือกทั้งหมดแล้ว')};
  const saveToSession=async(session:CountSession)=>{if(!selectedCount){setMessage('กรุณาเลือกรายการที่พบใน Allowance อย่างน้อย 1 รายการ');return;}try{setSaving(true);await auditRepository.addMovement(file,rows,session,session.auditorName);await db.movementDrafts.delete('movement');nav('/count');}catch(e){setMessage(e instanceof Error?`ไม่สามารถนำรายการไปนับได้: ${e.message}`:'ไม่สามารถนำรายการไปนับได้ กรุณาลองใหม่');}finally{setSaving(false)}};
  const useRows=async()=>{if(!selectedCount){setMessage('กรุณาเลือกรายการที่พบใน Allowance อย่างน้อย 1 รายการ');return;}if(!active){setSessionOpen(true);return;}await saveToSession(active)};
  const create=async()=>{if(!form.branchName||!form.auditorName){setMessage('กรุณากรอกชื่อสาขาและชื่อผู้ตรวจนับ');return;}try{setSaving(true);const id=await auditRepository.createSession({...form,countDate:new Date(form.countDate)});const session=await db.countSessions.get(id);if(session)await saveToSession(session);}catch(e){setMessage(e instanceof Error?`สร้างรอบนับไม่สำเร็จ: ${e.message}`:'สร้างรอบนับไม่สำเร็จ');setSaving(false)}};
  return <Page title="ไฟล์รายการเคลื่อนไหว" subtitle="อ่าน A = รหัสสินค้า, C = ชื่อสินค้า, D = หน่วยนับ และจับคู่กับ Allowance"><section className="panel"><FileDrop label="เลือกไฟล์รายการเคลื่อนไหว" onFile={handle}/>{rows.length>0&&<><div className="mt-5"><MatchSummaryCards items={[{label:'ทั้งหมด',value:rows.length},{label:'พบ Allowance',value:matchedCount},{label:'ไม่พบ',value:missing.length,tone:'text-amber-600'},{label:'ซ้ำ',value:rows.filter(r=>r.status==='duplicate').length},{label:'ไม่ครบ',value:rows.filter(r=>r.status==='invalid').length},{label:'เลือกไปนับ',value:selectedCount,tone:'text-rose-700'}]}/></div><div className="mt-5 flex flex-wrap gap-2"><button type="button" className="btn-quiet" disabled={!matchedCount} onClick={selectAll}>เลือกทั้งหมด ({matchedCount})</button><button type="button" className="btn-quiet" disabled={!selectedCount} onClick={clearAll}>ยกเลิกทั้งหมด</button><button type="button" className="btn-quiet" disabled={!missing.length} onClick={()=>{const ws=XLSX.utils.json_to_sheet(missing.map(x=>({'รหัสสินค้า':x.productCode,'ชื่อสินค้า':x.sourceProductName,'หน่วยนับ':x.sourceUnit,'เหตุผล':x.matchReason})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'ไม่พบใน Allowance');XLSX.writeFile(wb,'Unmatched_Allowance.xlsx')}}>Export รายการไม่พบ</button></div><div className="mt-4"><MovementImportPreview rows={rows} onToggle={i=>updateRows(current=>current.map((row,index)=>index===i&&row.matched?{...row,selected:!row.selected}:row))}/></div><button type="button" className="btn-primary mt-4 w-full" disabled={!selectedCount||saving} onClick={useRows}>{saving?'กำลังนำรายการเข้ารอบนับ...':`นำรายการที่เลือกไปนับสต็อก (${selectedCount})`}</button></>}</section>{message&&<div className="notice">{message}</div>}{sessionOpen&&<div className="modal-backdrop"><form className="modal-card max-w-lg" onSubmit={e=>{e.preventDefault();create()}}><p className="eyebrow">NEW COUNT SESSION</p><h2 className="text-2xl font-black">เริ่มรอบนับใหม่</h2><div className="mt-5 grid gap-4"><label>ชื่อสาขา<input className="input mt-1" value={form.branchName} onChange={e=>setForm({...form,branchName:e.target.value})} required/></label><label>วันที่ตรวจนับ<input className="input mt-1" type="date" value={form.countDate} onChange={e=>setForm({...form,countDate:e.target.value})} required/></label><label>ชื่อผู้ตรวจนับ<input className="input mt-1" value={form.auditorName} onChange={e=>setForm({...form,auditorName:e.target.value})} required/></label><label>หมายเหตุ<textarea className="input mt-1 min-h-20" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" className="btn-secondary" onClick={()=>setSessionOpen(false)}>ยกเลิก</button><button className="btn-primary" disabled={saving}>{saving?'กำลังสร้าง...':'สร้างรอบนับ'}</button></div></form></div>}</Page>
}
