import {AlertTriangle,CheckCircle2,FileUp} from 'lucide-react';
import type {ParsedMovement,ParsedProduct} from '../types';

export function MatchSummaryCards({items}:{items:{label:string;value:number;tone?:string}[]}){return <div className="summary-cards">{items.map(item=><div key={item.label} className="metric-card"><span>{item.label}</span><b className={item.tone||''}>{item.value.toLocaleString('th-TH')}</b></div>)}</div>}

export function FileDrop({onFile,label}:{onFile:(file:File)=>void;label:string}){return <label className="file-drop"><FileUp aria-hidden="true"/><b>{label}</b><span>แตะเพื่อเลือกไฟล์ รองรับ .xlsx และ .xls</span><input className="sr-only" type="file" accept=".xlsx,.xls" onChange={event=>event.target.files?.[0]&&onFile(event.target.files[0])}/></label>}

export function AllowanceImportPreview({rows}:{rows:ParsedProduct[]}){return <div className="table-scroll" role="region" aria-label="ตัวอย่างข้อมูล Allowance" tabIndex={0}><table><thead><tr><th>แถว</th><th>รหัสสินค้า</th><th>ชื่อสินค้า</th><th>หน่วย</th><th>ผลตรวจ</th></tr></thead><tbody>{rows.slice(0,50).map((row,index)=><tr key={index}><td>{row.row}</td><td className="font-mono">{row.productCode}</td><td className="wrap-cell">{row.productName}</td><td>{row.unit}</td><td><Status ok={row.status==='insert'||row.status==='update'||row.status==='skip'} text={row.status||''}/></td></tr>)}</tbody></table></div>}

function Status({ok,text}:{ok:boolean;text:string}){return <span className={ok?'status-pill status-ok':'status-pill status-warning'}>{ok?<CheckCircle2/>:<AlertTriangle/>}<span>{text}</span></span>}

export function MovementImportPreview({rows,onToggle}:{rows:ParsedMovement[];onToggle:(index:number)=>void}){return <>
  <div className="movement-mobile-list">{rows.map((row,index)=><article className="movement-card" key={`${row.productCode}-${index}`}><label className="movement-select"><input aria-label={`เลือกรายการ ${row.productCode}`} type="checkbox" checked={!!row.selected} disabled={!row.matched} onChange={()=>onToggle(index)}/><span>เลือกไปนับ</span></label><code>{row.productCode}</code><h3>{row.product?.productName||row.sourceProductName||'-'}</h3><dl><div><dt>ชื่อจากไฟล์</dt><dd>{row.sourceProductName||'-'}</dd></div><div><dt>หน่วย</dt><dd>{row.product?.unit||row.sourceUnit||'-'}</dd></div><div><dt>หมวด</dt><dd>{row.product?.categoryName||'-'}</dd></div></dl><Status ok={!!row.matched} text={row.matchReason||''}/></article>)}</div>
  <div className="movement-desktop-table table-scroll" role="region" aria-label="ตารางรายการเคลื่อนไหว" tabIndex={0}><table><thead><tr><th>เลือก</th><th>รหัสสินค้า</th><th>ชื่อจากไฟล์</th><th>ชื่อจาก Allowance</th><th>หน่วยนับ</th><th>หมวดสินค้า</th><th>สถานะ</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${row.productCode}-${index}`}><td><input aria-label={`เลือกรายการ ${row.productCode}`} className="table-checkbox" type="checkbox" checked={!!row.selected} disabled={!row.matched} onChange={()=>onToggle(index)}/></td><td className="font-mono">{row.productCode}</td><td className="wrap-cell">{row.sourceProductName}</td><td className="wrap-cell">{row.product?.productName||'-'}</td><td>{row.product?.unit||row.sourceUnit}</td><td>{row.product?.categoryName||'-'}</td><td><Status ok={!!row.matched} text={row.matchReason||''}/></td></tr>)}</tbody></table></div>
</>}
