import * as XLSX from 'xlsx'; import type {CountSession,CountSessionItem,CountTransaction,ParsedMovement,ParsedProduct,Product} from '../types';
export function normalizeProductCode(value:unknown):string{if(value===null||value===undefined)return '';let s=String(value).trim().replace(/^'/,'');if(/^[+-]?\d+(?:\.\d+)?[eE][+-]?\d+$/.test(s)){const [co,ex]=s.toLowerCase().split('e');const neg=co.startsWith('-');const c=co.replace(/^[-+]/,'');const [a,b='']=c.split('.');const digits=a+b;const point=a.length+Number(ex);s=point<=0?'0.'+'0'.repeat(-point)+digits:point>=digits.length?digits+'0'.repeat(point-digits.length):digits.slice(0,point)+'.'+digits.slice(point);if(neg)s='-'+s;}return s.replace(/^(\d+)\.0+$/,'$1');}
const tidy=(v:unknown)=>String(v??'').trim();
const headerKey=(v:unknown)=>tidy(v).replace(/\s/g,'').toLowerCase();
function locate(headers:unknown[],names:string[],fallback:number){const i=headers.findIndex(h=>names.some(n=>headerKey(h).includes(n)));return i>=0?i:fallback;}
export function parseAllowanceWorkbook(data:ArrayBuffer):ParsedProduct[]{const wb=XLSX.read(data,{type:'array',raw:false});const rows=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[wb.SheetNames[0]],{header:1,defval:'',raw:false});if(!rows.length)throw new Error('ไม่พบข้อมูลในไฟล์ Allowance');let hi=rows.findIndex(r=>r.some(c=>['รหัสสินค้า','productcode','รหัส'].some(k=>headerKey(c).includes(k))));if(hi<0)hi=0;const h=rows[hi];const ci=locate(h,['รหัสสินค้า','productcode','code'],0),ni=locate(h,['ชื่อสินค้า','productname','description'],1),ui=locate(h,['หน่วยนับ','unit'],2),cci=locate(h,['หมวด','categorycode'],3),cni=locate(h,['หมวดสินค้า','categoryname'],4);return rows.slice(hi+1).map((r,i)=>({row:hi+i+2,productCode:normalizeProductCode(r[ci]),productName:tidy(r[ni]),unit:tidy(r[ui]),categoryCode:tidy(r[cci]),categoryName:tidy(r[cni])})).filter(x=>x.productCode||x.productName);}
export function parseMovementWorkbook(data:ArrayBuffer):ParsedMovement[]{const wb=XLSX.read(data,{type:'array',raw:false});const rows=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[wb.SheetNames[0]],{header:1,defval:'',raw:false});if(!rows.length)throw new Error('ไม่พบข้อมูลในไฟล์รายการเคลื่อนไหว');let hi=rows.findIndex(r=>r.some(c=>['รหัสสินค้า','productcode','itemcode'].some(k=>headerKey(c).includes(k))));const start=hi>=0?hi+1:Math.min(2,rows.length);const h=hi>=0?rows[hi]:[];const ci=hi>=0?locate(h,['รหัสสินค้า','productcode','itemcode'],0):0,ni=hi>=0?locate(h,['ชื่อสินค้า','productname','description'],2):2,ui=hi>=0?locate(h,['หน่วยนับ','unit'],3):3,bi=hi>=0?locate(h,['ยอดคงเหลือ','balance','คงเหลือ'],14):14;return rows.slice(start).map((r,i)=>{const code=normalizeProductCode(r[ci]);const raw=String(r[bi]??'').replace(/,/g,'');return{row:start+i+1,productCode:code,sourceProductName:tidy(r[ni]),sourceUnit:tidy(r[ui]),sourceBalance:raw!==''&&Number.isFinite(Number(raw))?Number(raw):undefined};}).filter(x=>x.productCode);}
export function compareAllowance(rows:ParsedProduct[],existing:Product[]){const seen=new Map<string,number>();rows.forEach(r=>seen.set(r.productCode,(seen.get(r.productCode)||0)+1));const map=new Map(existing.map(p=>[p.productCode,p]));return rows.map(r=>{if(!r.productCode||!r.productName||!r.unit)return{...r,status:'invalid' as const,error:'ข้อมูลสำคัญไม่ครบ'};if((seen.get(r.productCode)||0)>1)return{...r,status:'duplicate' as const,error:'รหัสซ้ำในไฟล์'};const old=map.get(r.productCode);if(!old)return{...r,status:'insert' as const};const same=['productName','unit','categoryCode','categoryName'].every(k=>old[k as keyof Product]===r[k as keyof ParsedProduct]);return{...r,status:same?'skip' as const:'update' as const};});}
export function matchMovementWithProducts(rows:ParsedMovement[],products:Product[]){const map=new Map(products.map(p=>[p.productCode,p]));const seen=new Set<string>();return rows.map(r=>{if(!r.productCode)return{...r,status:'invalid' as const,matched:false,matchReason:'ไม่มีรหัสสินค้า',selected:false};if(seen.has(r.productCode))return{...r,status:'duplicate' as const,matched:false,matchReason:'รหัสซ้ำในไฟล์',selected:false};seen.add(r.productCode);const product=map.get(r.productCode);return{...r,status:'valid' as const,product,matched:!!product,matchReason:product?'พบใน Allowance':'ไม่พบใน Allowance',selected:!!product};});}
export function calculateProductTotal(tx:CountTransaction[]){return tx.reduce((s,t)=>s+t.signedQuantity,0);}
export function formatThaiDateTime(d:Date|string){return new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d));}
export function createSessionNumber(now=new Date(),sequence=1){const d=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('');return`AUD-STOCK-${d}-${String(sequence).padStart(3,'0')}`;}
function setupSheet(ws:XLSX.WorkSheet,widths:number[]){ws['!autofilter']={ref:ws['!ref']||'A1:A1'};ws['!freeze']={xSplit:0,ySplit:1};ws['!cols']=widths.map(w=>({wch:w}));}
export function buildCountWorkbook(session:CountSession,items:CountSessionItem[],tx:CountTransaction[],unmatched:ParsedMovement[]=[]){const summary=items.map((it,i)=>{const t=tx.filter(x=>x.productCode===it.productCode);const latest=[...t].sort((a,b)=>+new Date(b.countedAt)-+new Date(a.countedAt))[0];return{'ลำดับ':i+1,'เลขที่รอบนับ':session.sessionNumber,'สาขา':session.branchName,'วันที่ตรวจ':new Date(session.countDate),'รหัสสินค้า':it.productCode,'ชื่อสินค้า':it.productNameSnapshot,'หน่วยนับ':it.unitSnapshot,'จำนวนเพิ่มรวม':t.filter(x=>x.action==='ADD').reduce((s,x)=>s+x.quantity,0),'จำนวนลบรวม':t.filter(x=>x.action==='SUBTRACT').reduce((s,x)=>s+x.quantity,0),'ยอดสุทธิ':calculateProductTotal(t),'จำนวนครั้งที่บันทึก':t.length,'วันที่และเวลาล่าสุด':latest?new Date(latest.countedAt):'','ผู้ตรวจนับล่าสุด':latest?.countedBy||'','หมายเหตุล่าสุด':latest?.note||''};});const history=[...tx].sort((a,b)=>+new Date(a.countedAt)-+new Date(b.countedAt)).map((t,i)=>({'ลำดับ':i+1,'เลขที่รอบนับ':session.sessionNumber,'สาขา':session.branchName,'รหัสสินค้า':t.productCode,'ชื่อสินค้า':t.productNameSnapshot,'ประเภทรายการ':t.action==='ADD'?'เพิ่ม':'ลบ','จำนวน':t.quantity,'จำนวนแบบมีเครื่องหมาย':t.signedQuantity,'ยอดก่อน':t.previousTotal,'ยอดหลัง':t.newTotal,'หมายเหตุ':t.note,'ผู้ตรวจนับ':t.countedBy,'วันที่':new Date(t.countedAt),'เวลา':new Date(t.countedAt).toLocaleTimeString('th-TH'),'วันที่และเวลาเต็ม':new Date(t.countedAt)}));const missing=unmatched.map((r,i)=>({'ลำดับ':i+1,'รหัสสินค้าจากไฟล์เคลื่อนไหว':r.productCode,'ชื่อสินค้า':r.sourceProductName,'หน่วยนับ':r.sourceUnit,'ชื่อไฟล์':session.movementFileName||'','เหตุผล':r.matchReason||'ไม่พบใน Allowance','วันที่ Import':new Date()}));const wb=XLSX.utils.book_new();[[summary,'สรุปการนับ'],[history,'ประวัติการนับ'],[missing,'รายการไม่พบใน Allowance']].forEach(([data,name])=>{const ws=XLSX.utils.json_to_sheet(data as object[]);setupSheet(ws,[8,24,18,16,18,36,14,16,16,14,18,22,22,30]);XLSX.utils.book_append_sheet(wb,ws,name as string);});return wb;}
export function exportCountSessionToExcel(session:CountSession,items:CountSessionItem[],tx:CountTransaction[],unmatched:ParsedMovement[]=[]){const wb=buildCountWorkbook(session,items,tx,unmatched);const stamp=new Date().toISOString().slice(0,16).replace('T','_').replace(':','');XLSX.writeFile(wb,`Audit_Stock_Count_${session.branchName}_${stamp}.xlsx`);}
